version: '3.8'

services:
  configurationaccessclientdemo:
    image: configurationaccessclientdemo
    build:
      context: .
      dockerfile: ConfigurationAccessClientDemo/Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_CONNECTION_STRING=redis:6379,abortConnect=false
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
